[build]
  base = "frontend"
  publish = "build"
  command = "npm ci && CI= GENERATE_SOURCEMAP=false npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NETLIFY_USE_YARN = "false"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 